---
image: "ruby:2.6"

before_script:
  - gem install bundler --no-document
  - bundle install --jobs $(nproc) --path vendor/bundle "${FLAGS[@]}"

rspec:
  script:
    - bundle exec rspec
  tags:
    - docker
  artifacts:
    paths:
      - coverage/

pages:
  stage: deploy
  dependencies:
    - rspec
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 7 days
