---
image: "ruby:2.5"

cache:
  paths:
    - vendor/bundle
    - vendor/apt

variables:
  BUNDLE_PATH: vendor/bundle

before_script:
  - export APT_CACHE_DIR=`pwd`/vendor/apt && mkdir -pv $APT_CACHE_DIR
  - apt-get update -yq
  - apt-get -q -o dir::cache::archives="$APT_CACHE_DIR" install -y cmake
  - gem install bundler --no-document
  - bundle check || bundle install

stages:
  - Testing
  - Release

rspec:
  stage: Testing
  only:
    - master
    - merge_requests
    - tags
  script:
    - bundle exec rspec
  tags:
    - docker

nexus:
  stage: Release
  only:
    refs:
      - tags
    variables:
      - $NEXUS_PASS
      - $NEXUS_USER
  variables:
    NEXUS_URL: "https://nexus.synyx.de/content/repositories/gems"
  script:
    - mkdir -p ~/.gem
    - AUTH=$(echo -n "$NEXUS_USER:$NEXUS_PASS" | base64)
    - '/bin/echo -e ":url: $NEXUS_URL\n:authorization: Basic $AUTH\n" > ~/.gem/nexus'
    - bundle exec rake build
    - bundle exec gem nexus pkg/buchungsstreber-*.gem
  tags:
    - docker
