---
image: "ruby:2.5"

cache:
  paths:
    - vendor/bundle
    - vendor/apt

variables:
  BUNDLE_PATH: vendor/bundle

before_script:
  - export APT_CACHE_DIR=`pwd`/vendor/apt && mkdir -pv $APT_CACHE_DIR
  - apt-get update -yq
  - apt-get -q -o dir::cache::archives="$APT_CACHE_DIR" install -y cmake
  - gem install bundler --no-document
  - bundle check || bundle install --with=dev

stages:
  - Testing
  - Linting

rspec:
  stage: Testing
  script:
    - bundle exec rspec
  tags:
    - docker

Pronto:
  stage: Linting
  allow_failure: true
  except:
    - master
  script:
    - bundle exec pronto run -f gitlab -c 9aebae105c0785b9e21dcc71a4155c419dcec9aa
  tags:
    - docker
