---
image: "ruby:3.0"

cache:
  paths:
    - vendor/bundle

variables:
  BUNDLE_PATH: vendor/bundle

before_script:
  - gem install bundler --no-document
  - bundle check || bundle install

stages:
  - Testing
  - Linting
  - Release

rspec:
  stage: Testing
  only:
    - master
    - merge_requests
    - tags
  script:
    - bundle exec rspec
  tags:
    - docker

rubocop:
  stage: Linting
  allow_failure: true
  only:
    - merge_requests
  script:
    - ./bin/rubocop_changes
  tags:
    - docker

nexus:
  stage: Release
  only:
    refs:
      - tags
    variables:
      - $NEXUS_PASS
      - $NEXUS_USER
  variables:
    NEXUS_URL: "https://nexus.synyx.de/content/repositories/gems"
  script:
    - mkdir -p ~/.gem
    - AUTH=$(echo -n "$NEXUS_USER:$NEXUS_PASS" | base64)
    - '/bin/echo -e ":url: $NEXUS_URL\n:authorization: Basic $AUTH\n" > ~/.gem/nexus'
    - bundle exec rake build
    - bundle exec gem nexus pkg/buchungsstreber-*.gem
  tags:
    - docker
