---
AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable

Layout/LineLength:
  Max: 120

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/MultipleComparison:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/StderrPuts:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false

# Disable this, we are using the constants for Aruba/InProcess testing
Style/GlobalStdStream:
  Enabled: false
